// Code generated by Arduino IoT Cloud — adapted for manual device setup

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

// =====================================================================
// ⚠️  FILL IN YOUR CREDENTIALS BELOW
// =====================================================================

// Get these from Arduino Cloud → Devices → Your Device
const char DEVICE_LOGIN_NAME[] = "YOUR_DEVICE_ID_HERE";       // e.g., "a1b2c3d4-e5f6-..."
const char DEVICE_KEY[]        = "YOUR_SECRET_KEY_HERE";       // e.g., "ABCDEF1234567890"

// Get this from Arduino Cloud → Things → Weather Station → Thing ID (in the URL or metadata)
const char THING_ID[]          = "YOUR_THING_ID_HERE";         // e.g., "f7g8h9i0-j1k2-..."

// Your Wi-Fi credentials
const char SSID[]              = "YOUR_WIFI_SSID";             // Your Wi-Fi network name
const char PASS[]              = "YOUR_WIFI_PASSWORD";         // Your Wi-Fi password

// =====================================================================
// Cloud Variables — must match what you created in Arduino Cloud
// =====================================================================
float temperature;
float humidity;

// =====================================================================
// Connection Handler
// =====================================================================
WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

// =====================================================================
// Cloud Initialization
// =====================================================================
void initProperties() {
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);

  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL, 0.5);  // threshold: 0.5°C
  ArduinoCloud.addProperty(humidity,    READ, ON_CHANGE, NULL, 1.0);   // threshold: 1.0%
}
